export default {
    name:"person-outline",
    email:"mail-outline",
    password:"lock-closed-outline",
    norating:"No Rating Available",
    nocolorname:"Color Name Not Available",
    Colorunavailable:"Color Unavailable",
    Description:"Desription :",
    Rating:"Rating",
    ProductType:"ProductType",
    Price:"Price",
    PleaseEnterEmail:'Please Enter Email',
    Productlink:"Product link",
    websitelink:"Website link",
    LOGINWITHFACEBOOK :"LOG IN WITH FACEBOOK",
    Login:"Login",
    WelcomeHomeMyFriend:"Welcome Home My Friend",
    LOGIN:"LOG IN",
    Donthaveanaccount:"Dont have an account ?",
    LOGINWITHGOOGLE : "LOG IN WITH GOOGLE",
    ForgotPasword :"Forgot Pasword ?",
    PleaseEnterPassword:"Please Enter Password",
    Entervalidpassword:'Enter Valid Password Must Contain Atleast 8 Character, Capital & Lowercase Letter,Special & Numeric Character',
    PleaseEnterEmail:'Please Enter Email',
    PleaseEntervalidemailaddress:'Please Enter valid email address',
    RememberPasword:"Remember Pasword",
    Please:"Please",
    ForgotPasword:"Forgot Pasword ?",
    SIGNUP:"SIGN UP",
    Rs:'\u20B9',
    Webviewproduct:"Webviewproduct",
    Webview:"Webview",
    Email:"Email",
    Password:"Password",
    PleaseEnterName:"Please Enter Name",
    EnterValidName:"Enter Valid Name",
    PleaseEnterPasswordAgain:'Please Enter Password Again',
    PasswordAndRetypePasswordmustbesame:"Password And Retype Password must be same",
    Name:"Name",
    PasswordRetype:"Password Retype",
    TermsConditions :"Terms & Conditions",
    Alreadyhaveanaccount:"Already  have an account ?",
    Forgotpassword:"Forgotpassword?",
    SUBMIT:"SUBMIT",
    Notificationcausedapptoopenfrombackgroundstate:"Notification caused app to open from background state:",
    none:"none"
    


}